-- Run as MARKETPULSE_ROLE (or ACCOUNTADMIN if role permissions aren't set yet)
-- Creates the database and all schemas

USE ROLE ACCOUNTADMIN;

-- Database
CREATE DATABASE IF NOT EXISTS MARKETPULSE_DEV;

-- Grant access to our role
GRANT OWNERSHIP ON DATABASE MARKETPULSE_DEV TO ROLE MARKETPULSE_ROLE;
GRANT USAGE ON DATABASE MARKETPULSE_DEV TO ROLE MARKETPULSE_ROLE;

USE ROLE MARKETPULSE_ROLE;
USE DATABASE MARKETPULSE_DEV;

-- Schemas
CREATE SCHEMA IF NOT EXISTS APP;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MARTS;
CREATE SCHEMA IF NOT EXISTS SEMANTIC;

-- Verify
SHOW SCHEMAS IN DATABASE MARKETPULSE_DEV;
